#!/usr/bin/env node
import { mkdirSync, writeFileSync, copyFileSync, readdirSync, readFileSync, existsSync } from 'node:fs';
import { join, resolve, dirname } from 'node:path';
import { execSync } from 'node:child_process';
import { fileURLToPath } from 'node:url';

import { hydrateContext, renderTemplate, ratchetGenerator } from '@marcellelabs/swarm';
import type { SwarmContext } from '@marcellelabs/swarm';
import { detectProject } from './detect.js';
import { confirm, prompt, confirmDetection } from './confirm.js';

const __dirname = dirname(fileURLToPath(import.meta.url));

async function main(): Promise<void> {
  const projectRoot = resolve(process.cwd());

  console.log('');
  console.log('  create-swarm — AI Swarm Harness Bootstrap');
  console.log('  ===========================================');
  console.log('');

  console.log('Phase 1: Detecting project...');
  const detection = await detectProject(projectRoot);

  if (!detection.packageManager) {
    console.log('  WARNING: No package manager lockfile detected.');
  } else {
    console.log(`  Package manager: ${detection.packageManager}`);
  }
  console.log(`  Monorepo: ${detection.isMonorepo}`);
  console.log(`  Turbo: ${detection.hasTurbo}`);
  console.log(`  MCP config: ${detection.hasMcpJson}`);
  console.log(`  Langfuse: ${detection.hasLangfuse}`);
  console.log('');

  console.log('Phase 2: Hydrating context...');
  const context = await hydrateContext(projectRoot);

  console.log(`  Build command: ${context.buildCommand}`);
  console.log(`  Lint command: ${context.lintCommand}`);
  console.log(`  Test command: ${context.testCommand}`);
  console.log(`  Observability: ${context.observabilityBackend}`);
  console.log(`  Owned packages: ${context.ownedPackages.length}`);
  console.log('');

  console.log('Phase 3: Confirm detected values...');
  const shouldConfirm = await confirm('Confirm detected values before scaffolding?', true);
  if (shouldConfirm) {
    const overrides = await confirmDetection({
      packageManager: context.packageManager,
      buildCommand: context.buildCommand,
      lintCommand: context.lintCommand,
      testCommand: context.testCommand,
    });
    Object.assign(context, overrides);
  }
  console.log('');

  console.log('Phase 4: Writing ai-swarm.config.ts...');
  const configContent = generateConfigFile(context);
  const configPath = join(projectRoot, 'ai-swarm.config.ts');
  writeFileSync(configPath, configContent, 'utf8');
  console.log(`  Written: ${configPath}`);
  console.log('');

  console.log('Phase 5: Scaffolding .ai-swarm/ directory...');
  const swarmDir = join(projectRoot, '.ai-swarm');
  scaffoldDirectory(swarmDir, context);
  console.log('');

  console.log('Phase 6: Generating ratchet baselines...');
  try {
    const result = await ratchetGenerator(projectRoot);
    console.log(`  Written: ${result.path}`);
    console.log(`  Metrics: ${result.ratchets.map((r: { metric: string; baseline: number }) => `${r.metric}=${r.baseline}`).join(', ')}`);
  } catch (err) {
    console.log(`  WARNING: Ratchet generation failed: ${err}`);
  }
  console.log('');

  console.log('Phase 7: Initializing swarm state...');
  try {
    execSync(`bash ${join(swarmDir, 'scripts', 'swarm-state.sh')} init`, { cwd: projectRoot, stdio: 'pipe' });
    console.log('  State initialized.');
  } catch {
    console.log('  WARNING: swarm-state.sh init failed. Run manually after scaffolding.');
  }
  console.log('');

  console.log('Phase 8: Optional hook installation...');
  const installHooks = await confirm('Install worktree hooks (pre-commit gate guard)?', false);
  if (installHooks) {
    try {
      execSync(`bash ${join(swarmDir, 'scripts', 'install-worktree-hooks.sh')}`, { cwd: projectRoot, stdio: 'pipe' });
      console.log('  Hooks installed.');
    } catch {
      console.log('  WARNING: Hook installation failed. Run manually.');
    }
  }
  console.log('');

  console.log('  ===========================================');
  console.log('  Bootstrap complete!');
  console.log('  Next steps:');
  console.log('    1. Review .ai-swarm/agents/ for your project');
  console.log('    2. Review .ai-swarm/docs/reference/ for architecture fence');
  console.log('    3. Run: bash .ai-swarm/scripts/swarm-state.sh status');
  console.log('  ===========================================');
  console.log('');
}

function generateConfigFile(context: SwarmContext): string {
  return `// ai-swarm.config.ts — Project-specific overrides for the AI swarm harness
// Generated by create-swarm. Edit manually to override detected values.
import type { SwarmContext } from '@marcellelabs/swarm';

const config: Partial<SwarmContext> = {
  packageManager: '${context.packageManager}',
  buildCommand: '${context.buildCommand}',
  lintCommand: '${context.lintCommand}',
  testCommand: '${context.testCommand}',
  typecheckCommand: '${context.typecheckCommand}',
  branchModel: {
    main: '${context.branchModel.main}',
    dev: '${context.branchModel.dev}',
    prefix: '${context.branchModel.prefix}',
  },
  observabilityBackend: '${context.observabilityBackend}',
};

export default config;
`;
}

function scaffoldDirectory(swarmDir: string, context: SwarmContext): void {
  const templateRoot = join(__dirname, '..', 'templates');
  const packageTemplateRoot = resolveTemplateRoot();

  mkdirSync(join(swarmDir, 'agents'), { recursive: true });
  mkdirSync(join(swarmDir, 'scripts'), { recursive: true });
  mkdirSync(join(swarmDir, 'audit-templates'), { recursive: true });
  mkdirSync(join(swarmDir, 'docs', 'reference'), { recursive: true });
  mkdirSync(join(swarmDir, 'specs'), { recursive: true });
  mkdirSync(join(swarmDir, 'state', 'gates'), { recursive: true });

  copyAgentTemplates(packageTemplateRoot, swarmDir, context);
  copyShellScripts(packageTemplateRoot, swarmDir);
  copyAuditTemplates(packageTemplateRoot, swarmDir);
  copyReferenceFiles(packageTemplateRoot, swarmDir, context);
}

function resolveTemplateRoot(): string {
  const possible = [
    join(__dirname, '..', 'node_modules', '@marcellelabs', 'swarm', 'templates'),
    join(__dirname, '..', '..', 'swarm', 'templates'),
    join(__dirname, '..', 'templates'),
  ];
  for (const p of possible) {
    if (existsSync(join(p, 'agents'))) return p;
  }
  return possible[0];
}

function copyAgentTemplates(templateRoot: string, swarmDir: string, context: SwarmContext): void {
  const agentsDir = join(templateRoot, 'agents');
  if (!existsSync(agentsDir)) return;

  const files = readdirSync(agentsDir).filter((f) => f.endsWith('.md'));
  for (const file of files) {
    const src = join(agentsDir, file);
    const template = readFileSync(src, 'utf8');
    const rendered = renderTemplate(template, context);
    writeFileSync(join(swarmDir, 'agents', file), rendered, 'utf8');
  }
  console.log(`  Copied ${files.length} agent templates to .ai-swarm/agents/`);
}

function copyShellScripts(templateRoot: string, swarmDir: string): void {
  const scriptsDir = join(templateRoot, '..', 'scripts');
  if (!existsSync(scriptsDir)) return;

  const files = readdirSync(scriptsDir).filter((f) => f.endsWith('.sh'));
  for (const file of files) {
    const src = join(scriptsDir, file);
    copyFileSync(src, join(swarmDir, 'scripts', file));
  }
  console.log(`  Copied ${files.length} shell scripts to .ai-swarm/scripts/`);
}

function copyAuditTemplates(templateRoot: string, swarmDir: string): void {
  const auditDir = join(templateRoot, 'audit-templates');
  if (!existsSync(auditDir)) return;

  const files = readdirSync(auditDir).filter((f) => f.endsWith('.md'));
  for (const file of files) {
    const src = join(auditDir, file);
    copyFileSync(src, join(swarmDir, 'audit-templates', file));
  }
  console.log(`  Copied ${files.length} audit templates to .ai-swarm/audit-templates/`);
}

function copyReferenceFiles(templateRoot: string, swarmDir: string, context: SwarmContext): void {
  const refDir = join(swarmDir, 'docs', 'reference');

  const metaCanonPath = join(templateRoot, 'meta-canon.md');
  if (existsSync(metaCanonPath)) {
    const template = readFileSync(metaCanonPath, 'utf8');
    const rendered = renderTemplate(template, context);
    writeFileSync(join(swarmDir, 'meta-canon.md'), rendered, 'utf8');
    console.log('  Copied meta-canon.md');
  }

  const antiPatternsPath = join(templateRoot, 'anti-patterns.template.md');
  if (existsSync(antiPatternsPath)) {
    const template = readFileSync(antiPatternsPath, 'utf8');
    const rendered = renderTemplate(template, context);
    writeFileSync(join(refDir, 'anti-patterns.md'), rendered, 'utf8');
    console.log('  Copied anti-patterns.md to docs/reference/');
  }

  const archFencePath = join(templateRoot, 'architecture-fence.template.txt');
  if (existsSync(archFencePath)) {
    const template = readFileSync(archFencePath, 'utf8');
    const rendered = renderTemplate(template, context);
    writeFileSync(join(refDir, 'architecture-fence.txt'), rendered, 'utf8');
    console.log('  Copied architecture-fence.txt to docs/reference/');
  }

  const deferredWorkPath = join(templateRoot, 'deferred-work.template.md');
  if (existsSync(deferredWorkPath)) {
    copyFileSync(deferredWorkPath, join(refDir, 'deferred-work.md'));
    console.log('  Copied deferred-work.md to docs/reference/');
  }

  const ratchetPath = join(templateRoot, 'ratchet.template.json');
  if (existsSync(ratchetPath)) {
    copyFileSync(ratchetPath, join(swarmDir, 'ratchet.template.json'));
    console.log('  Copied ratchet.template.json');
  }
}

main().catch((err) => {
  console.error('Fatal error:', err);
  process.exit(1);
});
